/* --------------------------------------------------------------------------
   Cyberpunk city environment — shared types (P1-ART-09).

   The layout is pure data: every object in the world is a Placement that
   references a kit mesh (a key of kit-manifest.json) or a procedural box.
   Units are metres, three.js Y-up, +X east, −Z north. Yaw is degrees about +Y
   (three.js convention: a +90° yaw turns local −X to face world +Z).
   Design: docs/superpowers/specs/2026-09-29-landing-cyberpunk-city-design.md
   -------------------------------------------------------------------------- */

export type Vec3 = [number, number, number];

/** Collision layer. Ground tiles may sit under anything but never under each
 *  other; a venue surface (court, pitch, diamond) lies on the ground and may
 *  have props and structures standing on it, but never another surface; every
 *  other pair must be disjoint unless it shares a kit id. */
export type Layer = "ground" | "surface" | "structure" | "prop" | "air" | "venue";

export interface Bounds {
  min: Vec3;
  max: Vec3;
}

export interface Placement {
  /** Unique within the layout. */
  id: string;
  /** Kit mesh id (a key of kit-manifest.json `meshes`) or `box:<name>` for a
   *  procedural object, in which case `box` gives its local bounds. */
  mesh: string;
  /** World position of the object's local origin. */
  position: Vec3;
  /** Degrees about +Y. */
  yaw: number;
  /** Uniform or per-axis scale applied in local space before yaw. */
  scale: number | Vec3;
  layer: Layer;
  /** Placements sharing a kit id are allowed to interpenetrate (the storefront
   *  kit's base, front, tops and props are authored around one pivot). */
  kit?: string;
  /** Reporting only. */
  zone: string;
  /** `far` picks the decimated variant (`<mesh>__lod`) when the GLB has one. */
  lod?: "near" | "far";
  /** Local bounds for `box:` meshes; ignored for kit meshes. */
  box?: Bounds;
}

export interface Landmark {
  id: string;
  name: string;
  /** Ground-level anchor. */
  position: Vec3;
  /** Footprint size (x, y, z) where meaningful. */
  size?: Vec3;
  yaw?: number;
}

/* ---- Procedural venue specs — rendered by components, boxed for collision --- */

export interface BasketballCourtSpec {
  kind: "basketball";
  center: Vec3;
  /** Along local +X before yaw. FIBA: 28 × 15. */
  length: number;
  width: number;
  yaw: number;
  /** Rim height 3.05 m. Hoops face inward along the long axis. */
  hoopInset: number;
}

export interface SoccerPitchSpec {
  kind: "soccer";
  center: Vec3;
  /** Along local +X before yaw. Five-a-side: 40 × 20. */
  length: number;
  width: number;
  yaw: number;
  goalWidth: number;
  goalHeight: number;
}

export interface BaseballFieldSpec {
  kind: "baseball";
  /** Home plate, ground level. */
  home: Vec3;
  /** Direction (degrees, yaw) from home toward second base. */
  bisectorYaw: number;
  baseDistance: number;
  moundDistance: number;
  /** Outfield fence arc radius from home. */
  fenceRadius: number;
  backstopRadius: number;
}

export interface PedestalSpec {
  kind: "pedestal";
  center: Vec3;
  /** Bottom tier first. Octagonal. */
  tiers: { radius: number; height: number }[];
}

export interface SkyscraperSpec {
  kind: "skyscraper";
  /** Ground-level base centre. */
  base: Vec3;
  /** Total height including the kit tower's scaled mesh. */
  height: number;
}

export interface GantryScreenSpec {
  kind: "gantry";
  center: Vec3;
  /** Distance between the two posts (along local X before yaw). */
  span: number;
  yaw: number;
  postHeight: number;
  screen: { width: number; height: number; bottomY: number };
}

export interface CableSpec {
  kind: "cable";
  id: string;
  from: Vec3;
  to: Vec3;
  /** Midpoint sag in metres. */
  sag: number;
}

export type VenueSpec =
  | BasketballCourtSpec
  | SoccerPitchSpec
  | BaseballFieldSpec
  | PedestalSpec
  | SkyscraperSpec
  | GantryScreenSpec;

export interface CityLayout {
  site: Bounds;
  placements: Placement[];
  landmarks: Record<string, Landmark>;
  venues: VenueSpec[];
  cables: CableSpec[];
}

/* ---- Manifest (generated by scripts/city-kit, committed) ------------------- */

export interface ManifestMesh {
  file: string;
  dims: Vec3;
  min: Vec3;
  max: Vec3;
  tris: number;
  materials: string[];
}

export interface KitManifest {
  units: string;
  axes: string;
  meshes: Record<string, ManifestMesh>;
  materials: Record<
    string,
    {
      shader: string;
      textures: Partial<Record<"B" | "N" | "ORM" | "E" | "O" | "M" | "R" | "A" | "H" | "AORM" | "OTHER", string>>;
      emissiveIntensity: number | null;
      emissiveColor: number[] | null;
      baseColor: number[] | null;
    }
  >;
}
